### PR TITLE
Added BlogApp using Java Swing

### LINKED ISSUE #13: Complete Simple Blog command line project
A minimal command-line blog program implemented in Java. Create and view blog posts with ease.

Features
- Create new blog posts with titles and content.
- View all available blog posts.
- Simple and easy-to-use command-line interface.

[Example Usage](https://github.com/Janani-Balasooriya/Java-Beginner-Projects/blob/main/src/main/java/SimpleBlog/README.md)

### PR DESCRIPTION
**Pull request by HarshallSonawane**
fix #13 

1. HomePage

HomePage

2. Create Blog

CreateBlog

3. View Blogs 

ViewBlogs

### CODE REVIEW

**Comment by HarshallSonawane** [comment]
Hello @Janani-Balasooriya ,  
as suggested by you, I have completed the task.
Please accept my PR

**Comment by Janani-Balasooriya** [comment]
Hi @HarshallSonawane , I will review your pull request (PR) and will merge it asap. In the mean time please don't forget to star ⭐ this repo.
Thank you!

**Comment by HarshallSonawane** [comment]
Hello @Janani-Balasooriya may i know till when I would know the status of my PR

**Comment by Janani-Balasooriya** [comment]
Hi @HarshallSonawane I will do it within today.

**Review by Janani-Balasooriya — APPROVED** [review]

**Pull request merged**
