### PR TITLE
Implemented WeatherApp And updated README.

### PR DESCRIPTION
**Pull request by ShikariSohan**
A simple java based console Weather App.

screenshot

### CODE REVIEW

**Comment by ShikariSohan** [comment]
@Janani-Balasooriya  Please review it.

**Comment by ShikariSohan** [comment]
@Janani-Balasooriya please give PR approval. If any changes needed mention. Add hacktoberfest-accepted tag.

**Comment by Janani-Balasooriya** [comment]
@ShikariSohan The pull request should include only the necessary files. The other file changes aren't needed. Could you please update it? Once that’s done, I can go ahead and accept the PR. Thank you!
image

**Comment by ShikariSohan** [comment]
I do not quite understand what the issue is here. I have only created two files WeatherApp.java and a screenshot for the readme file I have updated. And now that the gitignore is here all the unnecessary files (build . idea etc) will be no issue. 
Which file should I remove? 
Please you will be kind enough to clarify this? 
@Janani-Balasooriya

**Review by Janani-Balasooriya — APPROVED** [review]

**Comment by Janani-Balasooriya** [comment]
Hi @ShikariSohan , thank you for your contribution. I've successfully merged your changes and looking forward to collaborating more in the future! ⭐🚀

#27

**Comment by ShikariSohan** [comment]
@Janani-Balasooriya You're welcome! I'm happy to hear that the changes have been helpful. 
By the way, if any project needs help or contributions, please let me know! I'd love to pitch in and collaborate on anything you’re working on. Let's make it even better together!

Feel free to connect with me on Discord at: ShikariSohan
And on LinkedIn: [https://www.linkedin.com/in/moksedur-rahman-sohan-53b514217](https://www.linkedin.com/in/moksedur-rahman-sohan-53b514217)

**Pull request merged**
