### PR TITLE
added the currencyConverter java program

### LINKED ISSUE #8: Complete Currency Converter project
A simple command-line currency converter implemented in Java. Convert an amount from one currency to another using exchange rates.

[Features](https://github.com/Janani-Balasooriya/Java-Beginner-Projects/blob/main/src/main/java/CurrencyConverter/README.md#features)
Convert an amount from one currency to another.
Supports multiple currency pairs (e.g., USD to EUR, USD to INR).
Fixed exchange rates for demonstration (if can fetch exchange rates from an external source/api).

### PR DESCRIPTION
**Pull request by SumitMangrati**
resolves #8 
added the currency converter program where the program asks the user for a input i.e in which mode of currency he/she is entering the value and then converts the following currency into all available currency modes (added around 5 currency exchange)

### CODE REVIEW

**Comment by Janani-Balasooriya** [comment]
Thank you for submitting the PR. It says 19 files has changed. I will review them asap.

**Comment by SumitMangrati** [comment]
all the other files were not staged because of which it shows 19 files changed

**Comment by Janani-Balasooriya** [comment]
This pull request is supposed to have only one file changed: CurrencyConverter.java

**Review by Janani-Balasooriya — CHANGES_REQUESTED** [review]
Only this file, 'CurrencyConverter.java,' should be included in this pull request. The others should be deleted.

**Review by Janani-Balasooriya — APPROVED** [review]

**Pull request merged**
