### PR TITLE
Added the Quiz Application Project!

### LINKED ISSUE #9: Complete Quiz Application project
A simple command-line quiz application implemented in Java. Create and take quizzes on various topics.

[Features](https://github.com/Janani-Balasooriya/Java-Beginner-Projects/blob/main/src/main/java/QuizApplication/README.md#features)
Create and customize quizzes with questions and answer choices.
Take quizzes and receive a score.
Supports multiple-choice questions.
Provides immediate feedback on correct and incorrect answers.

[Example questions for the quiz app](https://github.com/Janani-Balasooriya/Java-Beginner-Projects/blob/main/src/main/java/QuizApplication/README.md#example-questions-for-the-quiz-app)

### PR DESCRIPTION
**Pull request by MeetD99**
# Fixes
Added the Quiz Application Project which is a Command Line Quiz Application that asks General Knowledge Questions to the User and provides them with the Correct and Incorrect Answers immediately. It also Provides a Score at the End. The Questions added are 10 as of now but more can be added on will. 

Fix #9 by @MeetD99

# Description
- [ ] Bug Fix/ Hot Fix
- [x] Added a New Feature 
- [ ]  Refactored the Code

# Screenshot of the Command Line 
Capture

### CODE REVIEW

**Review by Janani-Balasooriya — CHANGES_REQUESTED** [review]
Hi @MeetD99 , You have done a great job! 

Can you please add the QuizApplication.java file inside the folder src/main/java/QuizApplication and do a commit?

Thank you!

**Comment by MeetD99** [comment]
Sure, I'll do it right away.

**Comment by MeetD99** [comment]
Hey @Janani-Balasooriya , I have successfully made another Commit. Please review it and let me know. Thanks a lot!

**Review by Janani-Balasooriya — CHANGES_REQUESTED** [review]
image

@MeetD99 , Could you please consider deleting the two files I marked from each folder? Then, this will be fine.

Thank you!

**Comment by MeetD99** [comment]
Alright @Janani-Balasooriya , It's done! Thanks.

**Review by Janani-Balasooriya — APPROVED** [review]

**Pull request merged**
